/**
 * @fileoverview Action-to-handler registry map (ES3-safe).
 * Maps every action string to its handler function (defined in actions_*.jsx).
 * REQUIRES: all actions_*.jsx loaded before this file
 * Load BEFORE: dispatcher.jsx
 */
// _handlers.jsx — Action-to-handler registry map (ES3-safe)
// REQUIRES: all actions_*.jsx loaded before this file
// Load BEFORE: dispatcher.jsx

var _handlers = {
  'createComp':           _handleCreateComp,
  'deleteComp':           _handleDeleteComp,
  'createTextLayer':      _handleCreateTextLayer,
  'createCameraLayer':    _handleCreateCameraLayer,
  'createLightLayer':     _handleCreateLightLayer,
  'createNullLayer':      _handleCreateNullLayer,
  'createAdjustmentLayer': _handleCreateAdjustmentLayer,
  'createShapeLayer':     _handleCreateShapeLayer,
  'createSolidLayer':     _handleCreateSolidLayer,
  'createRectangleLayer': _handleCreateRectangleLayer,
  'createEllipseLayer':   _handleCreateEllipseLayer,
  'createStarLayer':      _handleCreateStarLayer,
  'createSquircleLayer':  _handleCreateSquircleLayer,
  'createGearLayer':      _handleCreateGearLayer,
  'createWaveLayer':      _handleCreateWaveLayer,
  'createFlowerLayer':    _handleCreateFlowerLayer,
  'createPolygonLayer':   _handleCreatePolygonLayer,
  'addCompAsLayer':       _handleAddCompAsLayer,
  'clearLayerParent':     _handleClearLayerParent,
  'parkLayer':            _handleParkLayer,
  'unparkLayer':          _handleUnparkLayer,
  'deleteParkedLayer':    _handleDeleteParkedLayer,
  'deletePathLayer':      _handleDeletePathLayer,
  'setLayerProperty':     _handleSetLayerProperty,
  'setCompProperty':      _handleSetCompProperty,
  'setLayerParent':       _handleSetLayerParent,
  'setLayerOrder':        _handleSetLayerOrder,
  'moveLayerBefore':      _handleMoveLayerBefore,
  'renameNode':           _handleRenameNode,
  'focusComp':            _handleFocusComp,
  'listComps':            _handleListComps,
  'focusCompByName':      _handleFocusCompByName,
  'applyDynamicEffect':   _handleApplyDynamicEffect,
  'pollAliveEffects':     _handlePollAliveEffects,
  'removeEffect':         _handleRemoveEffect,
  'setEffectProperty':    _handleSetEffectProperty,
  'setExpression':        _handleSetExpression,
  'renameEffect':         _handleRenameEffect,
  'setEffectEnabled':     _handleSetEffectEnabled,
  'reorderEffect':        _handleReorderEffect,
  'reorderEffectChain':   _handleReorderEffectChain,
  'setLayerEnabled':      _handleSetLayerEnabled,
  'setLayerShy':          _handleSetLayerShy,
  'setCompHideShyLayers': _handleSetCompHideShyLayers,
  'restampLayer':         _handleRestampLayer,
  'pollAliveNodes':       _handlePollAliveNodes,
  'pollExternalDeletions': _handlePollExternalDeletions,
  'setBlendingMode':      _handleSetBlendingMode,
  'setLumaMatte':         _handleSetLumaMatte,
  'setAlphaMatte':        _handleSetAlphaMatte,
  'clearMatte':           _handleClearMatte,
  'getMasksForLayer':     _handleGetMasksForLayer,
  'batchGetLayerProperties': _handleBatchGetLayerProperties,
  'batchGetEffectProperties': _handleBatchGetEffectProperties,
  'readSchemaCache':      _handleReadSchemaCache,
  'writeSchemaCache':     _handleWriteSchemaCache,
  'getAEVersion':         _handleGetAEVersion,
  'introspectEffect':     _handleIntrospectEffect,
  'readGraph':            _handleReadGraph,
  'writeGraph':           _handleWriteGraph,
  'writeGraphExport':     _handleWriteGraphExport,
  'saveGraphToFile':      _handleSaveGraphToFile,
  'openGraphFile':        _handleOpenGraphFile,
  'ensureReservedComp':    _handleEnsureReservedComp,
  'browseAndImportFootage': _handleBrowseAndImportFootage,
  'createFootageLayer':    _handleCreateFootageLayer,
  'deleteFootageItem':     _handleDeleteFootageItem,
  'addKeyframe':           _handleAddKeyframe,
  'removeKeyframe':        _handleRemoveKeyframe,
  'removeAllKeyframes':    _handleRemoveAllKeyframes,
  'getKeyframeTimes':      _handleGetKeyframeTimes,
  'getCurrentTime':        _handleGetCurrentTime,
  'setCurrentTime':        _handleSetCurrentTime,
  'batchGetKeyframeTimes': _handleBatchGetKeyframeTimes,
  'getKeyframeData':       _handleGetKeyframeData,
  'writeCmdChunk':         _handleWriteCmdChunk,
  'executeCmdFile':        _handleExecuteCmdFile,
  'cleanupCmdFile':        _handleCleanupCmdFile,
  'enumerateAllEffects':   _handleEnumerateAllEffects,
  'buildFullEffectCatalog': _handleBuildFullEffectCatalog,
  'writeTextFile':          _handleWriteTextFile,
  'createCloner':          _handleCreateCloner,
  'removeCloner':          _handleRemoveCloner,
  'updateCloner':          _handleUpdateCloner,
  'importScanComps':       _handleImportScanComps,
  'importScanFootage':     _handleImportScanFootage,
  'importScanCompLayers':  _handleImportScanCompLayers,
  'stampImportUUIDs':      _handleStampImportUUIDs,
  'saveAsDialog':          _handleSaveAsDialog,
  'getProjectIdentifier':  _handleGetProjectIdentifier,
  'beginUndoGroup':        _handleBeginUndoGroup,
  'endUndoGroup':          _handleEndUndoGroup
};
